/* (C) Copyright 2009-2013 CNRS (Centre National de la Recherche Scientifique).

Licensed to the CNRS under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The CNRS licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.

*/

/* Contributors:

Luc Hogie (CNRS, I3S laboratory, University of Nice-Sophia Antipolis) 
Aurelien Lancin (Coati research team, Inria)
Christian Glacet (LaBRi, Bordeaux)
David Coudert (Coati research team, Inria)
Fabien Crequis (Coati research team, Inria)
Grégory Morel (Coati research team, Inria)
Issam Tahiri (Coati research team, Inria)
Julien Fighiera (Aoste research team, Inria)
Laurent Viennot (Gang research-team, Inria)
Michel Syska (I3S, Université Cote D'Azur)
Nathann Cohen (LRI, Saclay) 
Julien Deantoin (I3S, Université Cote D'Azur, Saclay) 

*/
 
 package grph.io;

import java.io.IOException;
import java.io.PrintStream;

import grph.Grph;
import toools.collections.primitive.IntCursor;

public class DimacsWriter extends AbstractGraphTextWriter
{
    @Override
    public void printGraph(Grph g, PrintStream os)
    {
	os.println("c This file was generated by Grph - http://www-sop.inria.fr/members/Luc.Hogie/grph/");
	os.println("p edge " + g.getVertices().size() + " " + g.getEdges().size());

	for (IntCursor ec : IntCursor.fromFastUtil(g.getEdges()))
	{
	    int e = ec.value;

	    // numbering starts at 1!!!
	    int v1 = g.getOneVertex(e);
	    int v2 = g.getTheOtherVertex(e, v1);
	    os.println("e " + (v1 + 1) + " " + (v2 + 1));
	}
    }

    public static void main(String[] args) throws IOException, ParseException, GraphBuildException
    {
	Grph g = new grph.in_memory.InMemoryGrph();
	g.addNVertices(50);
	g.glp();
	String s = new DimacsWriter().printGraph(g);
	System.out.println(s);
    }
    
    
    public static void printExampleCode()
    {
	Grph g = new grph.in_memory.InMemoryGrph();
	g.grid(2, 2);
	System.out.println(new DimacsWriter().printGraph(g));
	
    }
}
