/* (C) Copyright 2009-2013 CNRS (Centre National de la Recherche Scientifique).

Licensed to the CNRS under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The CNRS licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.

*/

/* Contributors:

Luc Hogie (CNRS, I3S laboratory, University of Nice-Sophia Antipolis) 
Aurelien Lancin (Coati research team, Inria)
Christian Glacet (LaBRi, Bordeaux)
David Coudert (Coati research team, Inria)
Fabien Crequis (Coati research team, Inria)
Grégory Morel (Coati research team, Inria)
Issam Tahiri (Coati research team, Inria)
Julien Fighiera (Aoste research team, Inria)
Laurent Viennot (Gang research-team, Inria)
Michel Syska (I3S, Université Cote D'Azur)
Nathann Cohen (LRI, Saclay) 
Julien Deantoin (I3S, Université Cote D'Azur, Saclay) 

*/
 
 package grph.io;


import java.io.PrintStream;

import grph.Grph;
import toools.collections.primitive.IntCursor;



/**
 * http://www.fim.uni-passau.de/en/fim/faculty/chairs/theoretische-informatik/projects.html
 * @author lhogie
 *
 */
public class GMLWriter extends AbstractGraphTextWriter
{

	@Override
	public  void printGraph(Grph g, PrintStream ps)
	{
		if (g.isHypergraph())
			throw new IllegalArgumentException("Cannot export an hypergraph to GraphML");
		

		ps.println("graph [");
		ps.println("\tcomment \"This graph was generated by Dipergrafs " + getClass().getName() + '"');
		ps.println("\tdirected 1");
		
		for (IntCursor c : IntCursor.fromFastUtil(g.getVertices()))
		{
			ps.println("\tnode [");
			ps.println("\t\tid " + c.value);
			ps.println("\t\tlabel " + c.value);
			ps.println("\t]");
		}

		for (IntCursor e : IntCursor.fromFastUtil(g.getEdges()))
		{
			ps.println("\tedge [");
			int v1 = g.getOneVertex(e.value);
			ps.println("\t\tsource " + v1);
			ps.println("\t\tdestination " + g.getTheOtherVertex(e.value, v1));
			ps.println("\t\tlabel " + e.value);
			ps.println("\t]");
		}

		ps.println("]");
		
	}
}
